export const testData = [
    {
        id: 1,
        name: 'Bitcoin',
        symbol: 'BTC',
        icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/1.png',
        price: '42,944.19',
        '24%': {
            movement: 'down',
            percent: '1.16'
        },
        marketCap: '841.62B',
        volume24H: {
            dollars: '$14,127,361,142',
            currency: '329,642 BTC',
        },
        circulatingSupply: {
            percent: 93,
            circulatingSupply: '19,598,606 BTC',
            maxSupply: '21,000,000 BTC'
        },
        chartData: [
         { name: 1, price: 50 },
         { name: 2, price: 55 },
         { name: 3, price: 48 },
         { name: 4, price: 60 },
         { name: 5, price: 52 },
         { day: 1, price: 20 },
        { day: 2, price: 70 },
        { day: 3, price: 38 },
        { day: 4, price: 89 },
        { day: 5, price: 52 },
         { name: 1, price: 50 },
         { name: 2, price: 55 },
         { name: 3, price: 48 },
         { day: 1, price: 100 },
         { day: 2, price: 30 },
         { day: 3, price: 48 },
         { day: 4, price: 89 },
         { day: 5, price: 52 },
         { name: 4, price: 60 },
         { name: 5, price: 52 },
         { name: 1, price: 50 },
         { name: 2, price: 55 },
         { name: 3, price: 48 },
         { name: 4, price: 60 },
         { day: 1, price: 20 },
            { day: 2, price: 70 },
            { day: 3, price: 38 },
            { day: 4, price: 89 },
            { day: 5, price: 52 },
         { name: 5, price: 52 },
         { name: 1, price: 50 },
         { name: 2, price: 55 },
         { name: 3, price: 48 },
         { day: 1, price: 100 },
         { day: 2, price: 30 },
         { day: 3, price: 48 },
         { day: 4, price: 89 },
         { day: 5, price: 52 },
         { name: 4, price: 60 },
         { name: 5, price: 52 },
     ]
    },
    {
        id: 2,
        name: 'Ethereum',
        symbol: 'ETH',
        icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/1027.png',
        price: '2,537.97',
        '24%': {
            movement: 'down',
            percent: '0.44'
        },
        marketCap: '304.93B',
        volume24H: {
            dollars: '9,580,653,056',
            currency: '3,766,948 ETH',
        },
        circulatingSupply: {
            percent: '100',
            circulatingSupply: '120,181,731 ETH',
            maxSupply: '120,181,731 ETH'
        },
        chartData: [
            { name: 1, price: 50 },
            { name: 2, price: 55 },
            { name: 3, price: 48 },
            { name: 4, price: 60 },
            { name: 5, price: 52 },
            { day: 1, price: 20 },
               { day: 2, price: 70 },
               { day: 3, price: 38 },
               { day: 4, price: 89 },
               { day: 5, price: 52 },
            { name: 1, price: 50 },
            { name: 2, price: 55 },
            { name: 3, price: 48 },
            { day: 1, price: 100 },
            { day: 2, price: 30 },
            { day: 3, price: 48 },
            { day: 4, price: 89 },
            { day: 5, price: 52 },
            { name: 4, price: 60 },
            { name: 5, price: 52 },
            { name: 1, price: 50 },
            { name: 2, price: 55 },
            { name: 3, price: 48 },
            { name: 4, price: 60 },
            { day: 1, price: 20 },
               { day: 2, price: 70 },
               { day: 3, price: 38 },
               { day: 4, price: 89 },
               { day: 5, price: 52 },
            { name: 5, price: 52 },
            { name: 1, price: 50 },
            { name: 2, price: 55 },
            { name: 3, price: 48 },
            { day: 1, price: 100 },
            { day: 2, price: 30 },
            { day: 3, price: 48 },
            { day: 4, price: 89 },
            { day: 5, price: 52 },
            { name: 4, price: 60 },
            { name: 5, price: 52 },
        ]
    },
    {
        id: 3,
        name: 'Internet Computer',
        symbol: 'ICP',
        icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/8916.png',
        price: '13.19',
        '24%': {
            movement: 'up',
            percent: '3.62'
        },
        marketCap: '6,005,361,901',
        volume24H: {
            dollars: '$218,202,986',
            currency: '16,579,512 ICP',
        },
        circulatingSupply: {
            percent: '100',
            circulatingSupply: '455,426,462 ICP',
            maxSupply: '455,426,462 ICP'
        },
        chartData: [
            { name: 1, price: 50 },
            { name: 2, price: 55 },
            { name: 3, price: 48 },
            { name: 4, price: 60 },
            { name: 5, price: 52 },
            { day: 1, price: 20 },
            { day: 2, price: 70 },
            { day: 3, price: 38 },
            { day: 4, price: 89 },
            { day: 5, price: 52 },
            { name: 1, price: 50 },
            { name: 2, price: 55 },
            { name: 3, price: 48 },
            { day: 1, price: 100 },
            { day: 2, price: 30 },
            { day: 3, price: 48 },
            { day: 4, price: 89 },
            { day: 5, price: 52 },
            { name: 4, price: 60 },
            { name: 5, price: 52 },
            { name: 1, price: 50 },
            { name: 2, price: 55 },
            { name: 3, price: 48 },
            { name: 4, price: 60 },
            { day: 1, price: 20 },
            { day: 2, price: 70 },
            { day: 3, price: 38 },
            { day: 4, price: 89 },
            { day: 5, price: 52 },
            { name: 5, price: 52 },
            { name: 1, price: 50 },
            { name: 2, price: 55 },
            { name: 3, price: 48 },
            { day: 1, price: 100 },
            { day: 2, price: 30 },
            { day: 3, price: 48 },
            { day: 4, price: 89 },
            { day: 5, price: 52 },
            { name: 4, price: 60 },
            { name: 5, price: 52 },
        ]
    }
]